on:
  # Atualização na branch “MASTER/MAIN” por push ou pull-request
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: python_rpa
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Coverage rpa
        run: coverage run rpa_python

      - name: Generate coverage report
        run: |
          coverage report
          coverage xml

